spring:
  datasource:
    url: jdbc:mysql://localhost:3306/AluCarros?&serverTimezone=UTC
    username: root
    password: senha1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect 
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
